### ISSUE TITLE
你好，请问现在还能进入代码复现交流群吗？

### ISSUE THREAD

**Issue by hj5717** [zhuwenxing/daily_arxiv#1]

**Comment by hj5717** [comment]
When will it be turned on again?




黄见
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuwenxing/daily_arxiv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuwenxing/daily_arxiv] 你好，请问现在还能进入代码复现交流群吗？ (Issue #1)





 
Closed #1 as completed.

**Comment by zhuwenxing** [comment]
https://user-images.githubusercontent.com/12268675/114894720-7650c600-9e41-11eb-8702-a2d95f1b1bee.jpg

可以再重新发送一下好友请求，之前是三个群都满员了，不打算再开新群了，所以把入群邀请关了（注释了）。
